#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

chown -R "$app:www-data" "$install_dir"

ynh_script_progression "Creating virtual environment"
python -m venv "$install_dir/venv"

ynh_script_progression "Installing dependencies in virtual environment"
$install_dir/venv/bin/pip install esphome

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

yunohost service add "$app" --description="ESPHome dashboard" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

ynh_config_add_nginx

# Create the fail2ban configuration
ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex='WARNING 401 POST \/login \(<HOST>\) \d*\.\d\dms$'

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#================================================
# END OF SCRIPT
#================================================

ynh_script_progression "Installation of $app completed"
