#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

ynh_script_progression "Creating virtual environment"
python -m venv "$install_dir/venv"
source "$install_dir/venv/bin/activate"

ynh_script_progression "Installing dependencies in virtual environment"
pip install -r "$install_dir/requirements.txt"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

yunohost service add "$app" --description="ESPHome dashboard" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# Create the fail2ban configuration
# TODO: Create the regex
ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."
